version: '3'
services:
  vcssync:
    # docker run -ti --env-file vcssync.env -v ${PWD}/build:/build \
    #  -v ${PWD}/mozharness:/mozharness vcssync_vcssync:latest \
    #  python mozharness/scripts/vcs-sync/vcs_sync.py -c mozharness/configs/vcs_sync/debug-test.py
    build:
      context: ./
      dockerfile: vcssync.dockerfile
    env_file: vcssync.env
    volumes:
      - ./mozharness:/mozharness
      - ./build:/build
      - ./python.py:/mozharness/mozharness/base/python.py
      - ./vcs_sync.py:/mozharness/scripts/vcs-sync/vcs_sync.py
      - ./debug-test.py:/mozharness/configs/vcs_sync/debug-test.py
    working_dir: /
    ports:
      - "5000:5000"
    command: python mozharness/scripts/vcs-sync/vcs_sync.py -c mozharness/configs/vcs_sync/debug-test.py

